#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Ukrainian translation script for additional OPNsense words
"""

import re
import sys

# Dictionary of additional word translations
additional_translations = {
    # Additional single words
    "Burst": "Сплеск",
    "Bytes": "Байти",
    "Caches": "Кеші",
    "Caddyfile": "Файл Caddy",
    "Candidate": "Кандидат",
    "Capabilities": "Можливості",
    "Capture": "Захоплення",
    "Child": "Дочірній",
    "Children": "Дочірні",
    "Circuits": "Схеми",
    "Clone": "Клонувати",
    "Collection": "Колекція",
    "Commands": "Команди",
    "Commit": "Зафіксувати",
    "Complexity": "Складність",
    "Compliance": "Відповідність",
    "Conditions": "Умови",
    "Confirmation": "Підтвердження",
    "Conn": "З'єднання",
    "Connections": "З'єднання",
    "Connector": "З'єднувач",
    "Constraints": "Обмеження",
    "Contacts": "Контакти",
    "Contents": "Вміст",
    "Cookies": "Кукі",
    "Cores": "Ядра",
    "Counters": "Лічильники",
    "Countries": "Країни",
    "Coverage": "Покриття",
    "Credentials": "Облікові дані",
    "Criteria": "Критерії",
    "Cronjob": "Завдання cron",
    "Cronjobs": "Завдання cron",
    "Cryptography": "Криптографія",
    "Currencies": "Валюти",
    "Cycles": "Цикли",
    "Databases": "Бази даних",
    "Datasets": "Набори даних",
    "Debugging": "Налагодження",
    "Decisions": "Рішення",
    "Decryption": "Розшифрування",
    "Defaults": "За замовчуванням",
    "Definitions": "Визначення",
    "Dependencies": "Залежності",
    "Deployment": "Розгортання",
    "Descriptions": "Описи",
    "Destinations": "Призначення",
    "Details": "Деталі",
    "Detection": "Виявлення",
    "Devices": "Пристрої",
    "Diagnostics": "Діагностика",
    "Dialogs": "Діалоги",
    "Differences": "Відмінності",
    "Directories": "Каталоги",
    "Disabled": "Вимкнено",
    "Disconnection": "Відключення",
    "Discovery": "Виявлення",
    "Disk": "Диск",
    "Disks": "Диски",
    "Distribution": "Розподіл",
    "Documents": "Документи",
    "Domains": "Домени",
    "Downloads": "Завантаження",
    "Drivers": "Драйвери",
    "Dumps": "Дампи",
    "Duplicates": "Дублікати",
    "Edges": "Краї",
    "Elements": "Елементи",
    "Emails": "Електронні листи",
    "Encryption": "Шифрування",
    "Endpoints": "Кінцеві точки",
    "Engines": "Двигуни",
    "Entries": "Записи",
    "Environments": "Середовища",
    "Episodes": "Епізоди",
    "Errors": "Помилки",
    "Events": "Події",
    "Examples": "Приклади",
    "Exceptions": "Винятки",
    "Exchanges": "Обміни",
    "Executions": "Виконання",
    "Experiments": "Експерименти",
    "Exports": "Експорти",
    "Extensions": "Розширення",
    "Externals": "Зовнішні",
    "Factors": "Фактори",
    "Failures": "Збої",
    "Features": "Функції",
    "Fields": "Поля",
    "Files": "Файли",
    "Filters": "Фільтри",
    "Fingerprints": "Відбитки",
    "Firewalls": "Брандмауери",
    "Flags": "Прапори",
    "Flows": "Потоки",
    "Folders": "Папки",
    "Formats": "Формати",
    "Forums": "Форуми",
    "Fragments": "Фрагменти",
    "Frames": "Кадри",
    "Frequencies": "Частоти",
    "Functions": "Функції",
    "Gateways": "Шлюзи",
    "Generations": "Покоління",
    "Generators": "Генератори",
    "Globals": "Глобальні",
    "Graphs": "Графіки",
    "Groups": "Групи",
    "Guards": "Охорона",
    "Guests": "Гості",
    "Guides": "Посібники",
    "Handlers": "Обробники",
    "Headers": "Заголовки",
    "Heights": "Висоти",
    "Histories": "Історії",
    "Hooks": "Гачки",
    "Hosts": "Хости",
    "Hostnames": "Імена хостів",
    "Hours": "Години",
    "Icons": "Іконки",
    "Identities": "Ідентичності",
    "Images": "Зображення",
    "Imports": "Імпорти",
    "Includes": "Включення",
    "Indexes": "Індекси",
    "Indicators": "Індикатори",
    "Industries": "Галузі",
    "Infections": "Інфекції",
    "Informations": "Інформація",
    "Inputs": "Входи",
    "Installations": "Встановлення",
    "Instances": "Екземпляри",
    "Instructions": "Інструкції",
    "Interfaces": "Інтерфейси",
    "Internals": "Внутрішні",
    "Intervals": "Інтервали",
    "Intrusions": "Вторгнення",
    "Items": "Елементи",
    "Jobs": "Завдання",
    "Joins": "Об'єднання",
    "Journals": "Журнали",
    "Jumps": "Переходи",
    "Keys": "Ключі",
    "Keywords": "Ключові слова",
    "Labels": "Мітки",
    "Languages": "Мови",
    "Layers": "Шари",
    "Layouts": "Макети",
    "Lengths": "Довжини",
    "Levels": "Рівні",
    "Libraries": "Бібліотеки",
    "Licenses": "Ліцензії",
    "Limits": "Обмеження",
    "Lines": "Рядки",
    "Links": "Посилання",
    "Lists": "Списки",
    "Listeners": "Слухачі",
    "Loads": "Навантаження",
    "Locals": "Локальні",
    "Locations": "Розташування",
    "Locks": "Блокування",
    "Logins": "Входи",
    "Logouts": "Виходи",
    "Loops": "Цикли",
    "Machines": "Машини",
    "Mails": "Пошта",
    "Managers": "Менеджери",
    "Manuals": "Посібники",
    "Maps": "Карти",
    "Marks": "Позначки",
    "Masks": "Маски",
    "Masters": "Головні",
    "Matches": "Збіги",
    "Materials": "Матеріали",
    "Maximums": "Максимуми",
    "Means": "Засоби",
    "Measures": "Заходи",
    "Members": "Члени",
    "Memories": "Пам'ять",
    "Menus": "Меню",
    "Messages": "Повідомлення",
    "Methods": "Методи",
    "Metrics": "Метрики",
    "Minimums": "Мінімуми",
    "Minutes": "Хвилини",
    "Mirrors": "Дзеркала",
    "Modes": "Режими",
    "Models": "Моделі",
    "Modules": "Модулі",
    "Monitors": "Монітори",
    "Months": "Місяці",
    "Mounts": "Монтування",
    "Moves": "Переміщення",
    "Multiples": "Множинні",
    "Names": "Імена",
    "Natives": "Рідні",
    "Networks": "Мережі",
    "Nodes": "Вузли",
    "Normals": "Нормальні",
    "Notes": "Примітки",
    "Notices": "Повідомлення",
    "Numbers": "Номери",
    "Objects": "Об'єкти",
    "Operations": "Операції",
    "Options": "Опції",
    "Orders": "Порядки",
    "Origins": "Походження",
    "Outputs": "Виходи",
    "Overrides": "Перевизначення",
    "Owners": "Власники",
    "Packages": "Пакети",
    "Pages": "Сторінки",
    "Panels": "Панелі",
    "Parameters": "Параметри",
    "Parents": "Батьківські",
    "Parts": "Частини",
    "Passes": "Проходи",
    "Passwords": "Паролі",
    "Paths": "Шляхи",
    "Patterns": "Шаблони",
    "Pauses": "Паузи",
    "Payloads": "Корисні навантаження",
    "Peers": "Однорангові",
    "Pendings": "Очікування",
    "Percents": "Відсотки",
    "Periods": "Періоди",
    "Permissions": "Дозволи",
    "Phases": "Фази",
    "Phones": "Телефони",
    "Pictures": "Зображення",
    "Pieces": "Частини",
    "Pings": "Пінги",
    "Places": "Місця",
    "Plans": "Плани",
    "Platforms": "Платформи",
    "Plugins": "Плагіни",
    "Points": "Точки",
    "Policies": "Політики",
    "Pools": "Пули",
    "Ports": "Порти",
    "Positions": "Позиції",
    "Posts": "Повідомлення",
    "Powers": "Потужності",
    "Prefixes": "Префікси",
    "Presents": "Присутні",
    "Presses": "Натискання",
    "Previouses": "Попередні",
    "Primaries": "Основні",
    "Prints": "Друк",
    "Priorities": "Пріоритети",
    "Privates": "Приватні",
    "Problems": "Проблеми",
    "Processes": "Процеси",
    "Products": "Продукти",
    "Profiles": "Профілі",
    "Programs": "Програми",
    "Projects": "Проекти",
    "Properties": "Властивості",
    "Protocols": "Протоколи",
    "Providers": "Постачальники",
    "Proxies": "Проксі",
    "Publics": "Публічні",
    "Pulls": "Витягування",
    "Purposes": "Цілі",
    "Pushes": "Натискання",
    "Qualities": "Якості",
    "Queries": "Запити",
    "Queues": "Черги",
    "Quicks": "Швидкі",
    "Quiets": "Тихі",
    "Quotes": "Цитати",
    "Randoms": "Випадкові",
    "Ranges": "Діапазони",
    "Rates": "Швидкості",
    "Reads": "Читання",
    "Readies": "Готові",
    "Reals": "Справжні",
    "Reasons": "Причини",
    "Receives": "Отримання",
    "Recents": "Останні",
    "Records": "Записи",
    "Recovers": "Відновлення",
    "Redirects": "Перенаправлення",
    "Reduces": "Зменшення",
    "References": "Посилання",
    "Refreshes": "Оновлення",
    "Regions": "Регіони",
    "Registers": "Реєстри",
    "Regulars": "Регулярні",
    "Rejects": "Відхилення",
    "Relations": "Відносини",
    "Releases": "Релізи",
    "Reloads": "Перезавантаження",
    "Remotes": "Віддалені",
    "Removes": "Видалення",
    "Renames": "Перейменування",
    "Repeats": "Повторення",
    "Replaces": "Заміни",
    "Replies": "Відповіді",
    "Reports": "Звіти",
    "Requests": "Запити",
    "Requires": "Вимоги",
    "Reserves": "Резерви",
    "Resets": "Скидання",
    "Resolves": "Вирішення",
    "Resources": "Ресурси",
    "Responses": "Відповіді",
    "Restarts": "Перезапуски",
    "Restores": "Відновлення",
    "Results": "Результати",
    "Resumes": "Продовження",
    "Retries": "Повторення",
    "Returns": "Повернення",
    "Reverses": "Зворотні",
    "Reviews": "Огляди",
    "Revokes": "Відкликання",
    "Rights": "Права",
    "Risks": "Ризики",
    "Roles": "Ролі",
    "Roots": "Корені",
    "Rotates": "Обертання",
    "Rounds": "Раунди",
    "Routes": "Маршрути",
    "Routers": "Маршрутизатори",
    "Routings": "Маршрутизація",
    "Rows": "Рядки",
    "Rules": "Правила",
    "Runs": "Запуски",
    "Safes": "Безпечні",
    "Samples": "Зразки",
    "Saves": "Збереження",
    "Scales": "Масштаби",
    "Scans": "Сканування",
    "Schedules": "Розклади",
    "Schemas": "Схеми",
    "Scopes": "Області",
    "Scores": "Оцінки",
    "Screens": "Екрани",
    "Scripts": "Скрипти",
    "Searches": "Пошуки",
    "Seconds": "Секунди",
    "Secrets": "Секрети",
    "Sections": "Розділи",
    "Secures": "Безпечні",
    "Securities": "Безпека",
    "Selects": "Вибори",
    "Sends": "Надсилання",
    "Sequences": "Послідовності",
    "Serials": "Серійні",
    "Series": "Серії",
    "Servers": "Сервери",
    "Services": "Служби",
    "Sessions": "Сесії",
    "Settings": "Налаштування",
    "Setups": "Налаштування",
    "Shares": "Спільні",
    "Shells": "Оболонки",
    "Shows": "Покази",
    "Shutdowns": "Вимкнення",
    "Signals": "Сигнали",
    "Simples": "Прості",
    "Singles": "Одиночні",
    "Sites": "Сайти",
    "Sizes": "Розміри",
    "Skips": "Пропуски",
    "Slaves": "Підлеглі",
    "Sleeps": "Сон",
    "Slows": "Повільні",
    "Smalls": "Малі",
    "Smarts": "Розумні",
    "Snapshots": "Знімки",
    "Sockets": "Сокети",
    "Softwares": "Програмне забезпечення",
    "Solutions": "Рішення",
    "Sorts": "Сортування",
    "Sources": "Джерела",
    "Spaces": "Простори",
    "Specials": "Спеціальні",
    "Speeds": "Швидкості",
    "Splits": "Розділення",
    "Stables": "Стабільні",
    "Stacks": "Стеки",
    "Stages": "Етапи",
    "Standards": "Стандарти",
    "Starts": "Початки",
    "States": "Стани",
    "Statics": "Статичні",
    "Stations": "Станції",
    "Statistics": "Статистика",
    "Statuses": "Статуси",
    "Steps": "Кроки",
    "Stops": "Зупинки",
    "Storages": "Сховища",
    "Stores": "Магазини",
    "Streams": "Потоки",
    "Strings": "Рядки",
    "Strongs": "Сильні",
    "Structures": "Структури",
    "Styles": "Стилі",
    "Subjects": "Теми",
    "Submits": "Надсилання",
    "Successes": "Успіхи",
    "Summaries": "Підсумки",
    "Supports": "Підтримка",
    "Switches": "Перемикачі",
    "Symbols": "Символи",
    "Syncs": "Синхронізація",
    "Systems": "Системи",
    "Tables": "Таблиці",
    "Tags": "Теги",
    "Targets": "Цілі",
    "Tasks": "Завдання",
    "Teams": "Команди",
    "Technicals": "Технічні",
    "Technologies": "Технології",
    "Templates": "Шаблони",
    "Terms": "Терміни",
    "Terminals": "Термінали",
    "Tests": "Тести",
    "Texts": "Тексти",
    "Themes": "Теми",
    "Threads": "Потоки",
    "Thresholds": "Пороги",
    "Tickets": "Квитки",
    "Times": "Часи",
    "Timeouts": "Тайм-аути",
    "Timers": "Таймери",
    "Titles": "Заголовки",
    "Tokens": "Токени",
    "Tools": "Інструменти",
    "Topics": "Теми",
    "Totals": "Всього",
    "Touches": "Дотики",
    "Tracks": "Треки",
    "Traffics": "Трафік",
    "Transfers": "Передачі",
    "Transforms": "Перетворення",
    "Translates": "Переклади",
    "Transports": "Транспорт",
    "Trees": "Дерева",
    "Triggers": "Тригери",
    "Trusts": "Довіра",
    "Tries": "Спроби",
    "Tunnels": "Тунелі",
    "Turns": "Повороти",
    "Types": "Типи",
    "Uniques": "Унікальні",
    "Units": "Одиниці",
    "Unknowns": "Невідомі",
    "Unlocks": "Розблокування",
    "Unsets": "Скасування",
    "Updates": "Оновлення",
    "Upgrades": "Оновлення",
    "Uploads": "Завантаження",
    "Usages": "Використання",
    "Users": "Користувачі",
    "Utilities": "Утиліти",
    "Valids": "Дійсні",
    "Values": "Значення",
    "Variables": "Змінні",
    "Vendors": "Постачальники",
    "Verifies": "Перевірки",
    "Versions": "Версії",
    "Videos": "Відео",
    "Views": "Перегляди",
    "Virtuals": "Віртуальні",
    "Visibles": "Видимі",
    "Visits": "Відвідування",
    "Volumes": "Томи",
    "Waits": "Очікування",
    "Wakes": "Пробудження",
    "Walks": "Ходьба",
    "Warnings": "Попередження",
    "Watches": "Спостереження",
    "Ways": "Шляхи",
    "Webs": "Веб",
    "Websites": "Веб-сайти",
    "Weeks": "Тижні",
    "Weights": "Ваги",
    "Welcomes": "Привітання",
    "Wides": "Широкі",
    "Windows": "Вікна",
    "Wires": "Дроти",
    "Wizards": "Майстри",
    "Works": "Роботи",
    "Worlds": "Світи",
    "Writes": "Записи",
    "Years": "Роки",
    "Zones": "Зони"
}

def translate_po_file_additional(filename):
    """Translate additional words in PO file"""
    with open(filename, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Count translations made
    translated_count = 0
    
    for english, ukrainian in additional_translations.items():
        # Pattern to match exact msgid with the English word
        pattern = f'msgid "{english}"\nmsgstr ""'
        replacement = f'msgid "{english}"\nmsgstr "{ukrainian}"'
        
        if pattern in content:
            content = content.replace(pattern, replacement)
            translated_count += 1
            print(f"Translated: {english} -> {ukrainian}")
    
    # Write back the file
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"\nTotal additional translations made: {translated_count}")
    return translated_count

if __name__ == "__main__":
    filename = "uk_UA.po"
    if len(sys.argv) > 1:
        filename = sys.argv[1]
    
    print(f"Adding additional word translations to {filename}...")
    translate_po_file_additional(filename)
    print("Additional word translation complete!")

