#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Ukrainian translation script for OPNsense short phrases
"""

import re
import sys

# Dictionary of short phrase translations
short_phrase_translations = {
    # Two-word phrases
    "Abort tests": "Перервати тести",
    "Absolutely silent": "Абсолютно тихо",
    "Access log": "Журнал доступу",
    "Access restrictions": "Обмеження доступу",
    "Add groups": "Додати групи",
    "Add new": "Додати новий",
    "Add template": "Додати шаблон",
    "Add widget": "Додати віджет",
    "Advanced configuration": "Розширена конфігурація",
    "Advanced features": "Розширені функції",
    "Advanced options": "Розширені параметри",
    "Alert info": "Інформація про сповіщення",
    "Alert selected": "Вибрані сповіщення",
    "Alert sid": "SID сповіщення",
    "Alias for": "Псевдонім для",
    "All packets": "Всі пакети",
    "Antenna settings": "Налаштування антени",
    "Any priority": "Будь-який пріоритет",
    "Apply changes": "Застосувати зміни",
    "Ask password": "Запитати пароль",
    "Auto detect": "Автовизначення",
    "Auto refresh": "Автооновлення",
    "Backup configuration": "Резервна конфігурація",
    "Basic authentication": "Базова автентифікація",
    "Basic configuration": "Базова конфігурація",
    "Basic settings": "Базові налаштування",
    "Block all": "Заблокувати все",
    "Block list": "Список блокування",
    "Browse files": "Переглянути файли",
    "Cache size": "Розмір кешу",
    "Cancel operation": "Скасувати операцію",
    "Certificate authority": "Центр сертифікації",
    "Certificate management": "Керування сертифікатами",
    "Change password": "Змінити пароль",
    "Check all": "Перевірити все",
    "Check connection": "Перевірити з'єднання",
    "Check status": "Перевірити статус",
    "Clear all": "Очистити все",
    "Clear cache": "Очистити кеш",
    "Clear log": "Очистити журнал",
    "Click here": "Натисніть тут",
    "Close window": "Закрити вікно",
    "Configuration backup": "Резервна копія конфігурації",
    "Configuration file": "Файл конфігурації",
    "Configuration saved": "Конфігурацію збережено",
    "Connection failed": "З'єднання не вдалося",
    "Connection status": "Статус з'єднання",
    "Connection successful": "З'єднання успішне",
    "Connection timeout": "Тайм-аут з'єднання",
    "Copy configuration": "Копіювати конфігурацію",
    "Create backup": "Створити резервну копію",
    "Create certificate": "Створити сертифікат",
    "Create new": "Створити новий",
    "Current configuration": "Поточна конфігурація",
    "Current status": "Поточний статус",
    "Custom configuration": "Користувацька конфігурація",
    "Custom settings": "Користувацькі налаштування",
    "Database connection": "З'єднання з базою даних",
    "Default configuration": "Конфігурація за замовчуванням",
    "Default gateway": "Шлюз за замовчуванням",
    "Default settings": "Налаштування за замовчуванням",
    "Delete all": "Видалити все",
    "Delete selected": "Видалити вибране",
    "Device information": "Інформація про пристрій",
    "Device status": "Статус пристрою",
    "Disable all": "Вимкнути все",
    "Download configuration": "Завантажити конфігурацію",
    "Download file": "Завантажити файл",
    "Edit configuration": "Редагувати конфігурацію",
    "Edit rule": "Редагувати правило",
    "Enable all": "Увімкнути все",
    "Enable logging": "Увімкнути журналювання",
    "Enter password": "Введіть пароль",
    "Error log": "Журнал помилок",
    "Error message": "Повідомлення про помилку",
    "Export configuration": "Експортувати конфігурацію",
    "Export data": "Експортувати дані",
    "File manager": "Менеджер файлів",
    "File upload": "Завантаження файлу",
    "Filter rules": "Правила фільтрації",
    "Firewall configuration": "Конфігурація брандмауера",
    "Firewall rules": "Правила брандмауера",
    "Firewall settings": "Налаштування брандмауера",
    "Generate certificate": "Згенерувати сертифікат",
    "Generate key": "Згенерувати ключ",
    "Global settings": "Глобальні налаштування",
    "Go back": "Повернутися",
    "Hardware information": "Інформація про апаратне забезпечення",
    "Import configuration": "Імпортувати конфігурацію",
    "Import data": "Імпортувати дані",
    "Install package": "Встановити пакет",
    "Interface configuration": "Конфігурація інтерфейсу",
    "Interface settings": "Налаштування інтерфейсу",
    "Interface status": "Статус інтерфейсу",
    "Invalid configuration": "Недійсна конфігурація",
    "Invalid input": "Недійсний ввід",
    "Last update": "Останнє оновлення",
    "Load configuration": "Завантажити конфігурацію",
    "Load default": "Завантажити за замовчуванням",
    "Local configuration": "Локальна конфігурація",
    "Log entries": "Записи журналу",
    "Log file": "Файл журналу",
    "Log settings": "Налаштування журналу",
    "Login failed": "Вхід не вдався",
    "Login successful": "Вхід успішний",
    "Logout now": "Вийти зараз",
    "Main configuration": "Головна конфігурація",
    "Main settings": "Головні налаштування",
    "Network configuration": "Конфігурація мережі",
    "Network interface": "Мережевий інтерфейс",
    "Network settings": "Налаштування мережі",
    "Network status": "Статус мережі",
    "New configuration": "Нова конфігурація",
    "New password": "Новий пароль",
    "No data": "Немає даних",
    "No results": "Немає результатів",
    "Not available": "Недоступно",
    "Not configured": "Не налаштовано",
    "Not connected": "Не підключено",
    "Operation failed": "Операція не вдалася",
    "Operation successful": "Операція успішна",
    "Package information": "Інформація про пакет",
    "Package management": "Керування пакетами",
    "Password policy": "Політика паролів",
    "Please wait": "Будь ласка, зачекайте",
    "Refresh page": "Оновити сторінку",
    "Remote configuration": "Віддалена конфігурація",
    "Remove all": "Видалити все",
    "Remove selected": "Видалити вибране",
    "Reset configuration": "Скинути конфігурацію",
    "Reset password": "Скинути пароль",
    "Restart service": "Перезапустити службу",
    "Restore backup": "Відновити резервну копію",
    "Restore configuration": "Відновити конфігурацію",
    "Save changes": "Зберегти зміни",
    "Save configuration": "Зберегти конфігурацію",
    "Search results": "Результати пошуку",
    "Security configuration": "Конфігурація безпеки",
    "Security policy": "Політика безпеки",
    "Security settings": "Налаштування безпеки",
    "Select all": "Вибрати все",
    "Select file": "Вибрати файл",
    "Select interface": "Вибрати інтерфейс",
    "Service configuration": "Конфігурація служби",
    "Service management": "Керування службами",
    "Service settings": "Налаштування служби",
    "Service started": "Службу запущено",
    "Service status": "Статус служби",
    "Service stopped": "Службу зупинено",
    "Show all": "Показати все",
    "Show details": "Показати деталі",
    "Show log": "Показати журнал",
    "Start service": "Запустити службу",
    "Stop service": "Зупинити службу",
    "System configuration": "Конфігурація системи",
    "System information": "Інформація про систему",
    "System settings": "Налаштування системи",
    "System status": "Статус системи",
    "Test configuration": "Тестова конфігурація",
    "Test connection": "Перевірити з'єднання",
    "Toggle all": "Перемкнути все",
    "Update available": "Доступне оновлення",
    "Update configuration": "Оновити конфігурацію",
    "Update system": "Оновити систему",
    "Upload configuration": "Завантажити конфігурацію",
    "Upload file": "Завантажити файл",
    "User configuration": "Конфігурація користувача",
    "User management": "Керування користувачами",
    "User settings": "Налаштування користувача",
    "View configuration": "Переглянути конфігурацію",
    "View details": "Переглянути деталі",
    "View log": "Переглянути журнал",
    
    # Additional common phrases
    "Access control": "Контроль доступу",
    "Account settings": "Налаштування облікового запису",
    "Active connections": "Активні з'єднання",
    "Add certificate": "Додати сертифікат",
    "Add interface": "Додати інтерфейс",
    "Add rule": "Додати правило",
    "Add user": "Додати користувача",
    "Administrator password": "Пароль адміністратора",
    "Allow access": "Дозволити доступ",
    "Authentication failed": "Автентифікація не вдалася",
    "Authentication method": "Метод автентифікації",
    "Authentication required": "Потрібна автентифікація",
    "Automatic backup": "Автоматична резервна копія",
    "Backup file": "Файл резервної копії",
    "Backup settings": "Налаштування резервного копіювання",
    "Block access": "Заблокувати доступ",
    "Certificate details": "Деталі сертифіката",
    "Certificate expired": "Сертифікат закінчився",
    "Certificate valid": "Сертифікат дійсний",
    "Configuration error": "Помилка конфігурації",
    "Configuration updated": "Конфігурацію оновлено",
    "Connection established": "З'єднання встановлено",
    "Connection lost": "З'єднання втрачено",
    "Create user": "Створити користувача",
    "Current user": "Поточний користувач",
    "Delete user": "Видалити користувача",
    "Deny access": "Заборонити доступ",
    "Device connected": "Пристрій підключено",
    "Device disconnected": "Пристрій відключено",
    "Edit user": "Редагувати користувача",
    "Enable service": "Увімкнути службу",
    "Error details": "Деталі помилки",
    "File downloaded": "Файл завантажено",
    "File uploaded": "Файл завантажено",
    "Firewall enabled": "Брандмауер увімкнено",
    "Firewall disabled": "Брандмауер вимкнено",
    "Interface down": "Інтерфейс вимкнено",
    "Interface up": "Інтерфейс увімкнено",
    "Invalid certificate": "Недійсний сертифікат",
    "Invalid password": "Недійсний пароль",
    "Invalid user": "Недійсний користувач",
    "Network down": "Мережа недоступна",
    "Network up": "Мережа доступна",
    "Password changed": "Пароль змінено",
    "Password expired": "Пароль закінчився",
    "Permission denied": "Дозвіл заборонено",
    "Service disabled": "Службу вимкнено",
    "Service enabled": "Службу увімкнено",
    "Service running": "Служба працює",
    "System ready": "Система готова",
    "System restart": "Перезапуск системи",
    "System shutdown": "Вимкнення системи",
    "User created": "Користувача створено",
    "User deleted": "Користувача видалено",
    "User updated": "Користувача оновлено"
}

def translate_po_file_short_phrases(filename):
    """Translate short phrases in PO file"""
    with open(filename, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Count translations made
    translated_count = 0
    
    for english, ukrainian in short_phrase_translations.items():
        # Pattern to match exact msgid with the English phrase
        pattern = f'msgid "{english}"\nmsgstr ""'
        replacement = f'msgid "{english}"\nmsgstr "{ukrainian}"'
        
        if pattern in content:
            content = content.replace(pattern, replacement)
            translated_count += 1
            print(f"Translated: {english} -> {ukrainian}")
    
    # Write back the file
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"\nTotal short phrase translations made: {translated_count}")
    return translated_count

if __name__ == "__main__":
    filename = "uk_UA.po"
    if len(sys.argv) > 1:
        filename = sys.argv[1]
    
    print(f"Adding short phrase translations to {filename}...")
    translate_po_file_short_phrases(filename)
    print("Short phrase translation complete!")
