#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Second batch Ukrainian translation script for OPNsense
"""

import re
import sys

def translate_batch2_terms():
    """Second batch translate terms"""
    
    # Read the file
    with open('uk_UA.po', 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Dictionary of translations
    translations = {
        # Single letter/short codes
        "C": "C",
        
        # Languages
        "Czech": "Чеська",
        "English": "Англійська", 
        "French": "Французька",
        "German": "Німецька",
        "Italian": "Італійська",
        "Japanese": "Японська",
        "Korean": "Корейська",
        
        # Days
        "Days": "Дні",
        "Fri": "П'ят",
        
        # Technical terms
        "Development": "Розробка",
        "Dir": "Каталог",
        "Disallow": "Заборонити",
        "Discard": "Відкинути",
        "Diversity": "Різноманітність",
        "Dnsmasq": "Dnsmasq",
        "Downtime": "Час простою",
        "Elapsed": "Минуло",
        "End": "Кінець",
        "Evaluations": "Оцінки",
        "Fileid": "ID файлу",
        "Flavour": "Варіант",
        "Floating": "Плаваючий",
        "Flush": "Очистити",
        "Forwarders": "Переспрямовувачі",
        "Freeradius": "Freeradius",
        "Garmin": "Garmin",
        "Generic": "Загальний",
        "Git": "Git",
        "Granularity": "Деталізація",
        "Groupname": "Ім'я групи",
        "Handshake": "Рукостискання",
        "Hiadaptive": "Високоадаптивний",
        "Hit": "Попадання",
        "Hold": "Утримувати",
        "Hostid": "ID хоста",
        "Iburst": "Iburst",
        "Identifier": "Ідентифікатор",
        "Ikeid": "IKE ID",
        "Incomplete": "Неповний",
        "Indoor": "Внутрішній",
        "Inspect": "Перевірити",
        "Int": "Ціле",
        "Introduction": "Вступ",
        "Inverse": "Обернений",
        "Invert": "Інвертувати",
        "Keyinfo": "Інформація про ключ",
        "Latency": "Затримка",
        "Legend": "Легенда",
        "Linkstate": "Стан з'єднання",
        
        # More technical terms
        "Data": "Дані",
        "Database": "База даних",
        "Date": "Дата",
        "Debug": "Налагодження",
        "Decode": "Декодувати",
        "Default": "За замовчуванням",
        "Delete": "Видалити",
        "Deleted": "Видалено",
        "Deleting": "Видалення",
        "Delivery": "Доставка",
        "Deny": "Заборонити",
        "Deploy": "Розгорнути",
        "Deployed": "Розгорнуто",
        "Deployment": "Розгортання",
        "Depth": "Глибина",
        "Description": "Опис",
        "Design": "Дизайн",
        "Desktop": "Робочий стіл",
        "Destination": "Призначення",
        "Detail": "Деталь",
        "Detailed": "Детальний",
        "Details": "Деталі",
        "Detect": "Виявити",
        "Detected": "Виявлено",
        "Detection": "Виявлення",
        "Device": "Пристрій",
        "Devices": "Пристрої",
        "Diagnostic": "Діагностика",
        "Diagnostics": "Діагностика",
        "Dialog": "Діалог",
        "Dialogs": "Діалоги",
        "Dictionary": "Словник",
        "Difference": "Різниця",
        "Differences": "Відмінності",
        "Different": "Різний",
        "Digital": "Цифровий",
        "Direct": "Прямий",
        "Direction": "Напрямок",
        "Directly": "Безпосередньо",
        "Directory": "Каталог",
        "Directories": "Каталоги",
        "Disable": "Вимкнути",
        "Disabled": "Вимкнено",
        "Disabling": "Вимкнення",
        "Disconnect": "Відключити",
        "Disconnected": "Відключено",
        "Disconnecting": "Відключення",
        "Disconnection": "Відключення",
        "Discover": "Виявити",
        "Discovery": "Виявлення",
        "Disk": "Диск",
        "Disks": "Диски",
        "Display": "Відображення",
        "Displayed": "Відображено",
        "Displaying": "Відображення",
        "Displays": "Дисплеї",
        "Distance": "Відстань",
        "Distribute": "Розподілити",
        "Distributed": "Розподілено",
        "Distribution": "Розподіл",
        "Document": "Документ",
        "Documentation": "Документація",
        "Documents": "Документи",
        "Domain": "Домен",
        "Domains": "Домени",
        "Done": "Готово",
        "Double": "Подвійний",
        "Down": "Вниз",
        "Download": "Завантажити",
        "Downloaded": "Завантажено",
        "Downloading": "Завантаження",
        "Downloads": "Завантаження",
        "Drive": "Диск",
        "Driver": "Драйвер",
        "Drivers": "Драйвери",
        "Drop": "Відкинути",
        "Dropped": "Відкинуто",
        "Dropping": "Відкидання",
        "Drops": "Відкидання",
        "Dual": "Подвійний",
        "Dump": "Дамп",
        "Dumps": "Дампи",
        "Duration": "Тривалість",
        "Dynamic": "Динамічний",
        "Dynamically": "Динамічно",
        
        # E terms
        "Each": "Кожен",
        "Early": "Рано",
        "Easy": "Легко",
        "Echo": "Ехо",
        "Edge": "Край",
        "Edges": "Краї",
        "Edit": "Редагувати",
        "Edited": "Відредаговано",
        "Editing": "Редагування",
        "Edition": "Видання",
        "Editor": "Редактор",
        "Effect": "Ефект",
        "Effective": "Ефективний",
        "Effectively": "Ефективно",
        "Effects": "Ефекти",
        "Efficiency": "Ефективність",
        "Efficient": "Ефективний",
        "Either": "Або",
        "Element": "Елемент",
        "Elements": "Елементи",
        "Email": "Електронна пошта",
        "Emails": "Електронні листи",
        "Emergency": "Аварійний",
        "Empty": "Порожній",
        "Enable": "Увімкнути",
        "Enabled": "Увімкнено",
        "Enabling": "Увімкнення",
        "Encode": "Кодувати",
        "Encoded": "Закодовано",
        "Encoding": "Кодування",
        "Encrypt": "Шифрувати",
        "Encrypted": "Зашифровано",
        "Encrypting": "Шифрування",
        "Encryption": "Шифрування",
        "End": "Кінець",
        "Ending": "Закінчення",
        "Endpoint": "Кінцева точка",
        "Endpoints": "Кінцеві точки",
        "Ends": "Закінчується",
        "Engine": "Двигун",
        "Engines": "Двигуни",
        "English": "Англійська",
        "Enhanced": "Покращений",
        "Enhancement": "Покращення",
        "Enhancements": "Покращення",
        "Enough": "Достатньо",
        "Ensure": "Забезпечити",
        "Enter": "Ввести",
        "Entered": "Введено",
        "Entering": "Введення",
        "Enterprise": "Підприємство",
        "Entire": "Весь",
        "Entirely": "Повністю",
        "Entries": "Записи",
        "Entry": "Запис",
        "Environment": "Середовище",
        "Environments": "Середовища",
        "Equal": "Рівний",
        "Equals": "Дорівнює",
        "Equipment": "Обладнання",
        "Error": "Помилка",
        "Errors": "Помилки",
        "Escape": "Екранувати",
        "Escaped": "Екрановано",
        "Essential": "Суттєвий",
        "Establish": "Встановити",
        "Established": "Встановлено",
        "Establishing": "Встановлення",
        "Estimate": "Оцінити",
        "Estimated": "Оцінено",
        "Estimation": "Оцінка",
        "Ethernet": "Ethernet",
        "European": "Європейський",
        "Evaluate": "Оцінити",
        "Evaluated": "Оцінено",
        "Evaluating": "Оцінювання",
        "Evaluation": "Оцінка",
        "Even": "Навіть",
        "Event": "Подія",
        "Events": "Події",
        "Ever": "Коли-небудь",
        "Every": "Кожен",
        "Everyone": "Кожен",
        "Everything": "Все",
        "Everywhere": "Всюди",
        "Evidence": "Докази",
        "Exact": "Точний",
        "Exactly": "Точно",
        "Example": "Приклад",
        "Examples": "Приклади",
        "Exceed": "Перевищити",
        "Exceeded": "Перевищено",
        "Exceeding": "Перевищення",
        "Exceeds": "Перевищує",
        "Excellent": "Відмінний",
        "Exception": "Виняток",
        "Exceptions": "Винятки",
        "Exchange": "Обмін",
        "Exchanged": "Обмінено",
        "Exchanges": "Обміни",
        "Exchanging": "Обмін",
        "Exclude": "Виключити",
        "Excluded": "Виключено",
        "Excluding": "Виключаючи",
        "Exclusion": "Виключення",
        "Exclusive": "Ексклюзивний",
        "Exclusively": "Виключно",
        "Execute": "Виконати",
        "Executed": "Виконано",
        "Executing": "Виконання",
        "Execution": "Виконання",
        "Executive": "Виконавчий",
        "Exist": "Існувати",
        "Existed": "Існував",
        "Existence": "Існування",
        "Existing": "Існуючий",
        "Exists": "Існує",
        "Exit": "Вихід",
        "Exited": "Вийшов",
        "Exiting": "Вихід",
        "Exits": "Виходи",
        "Expand": "Розширити",
        "Expanded": "Розширено",
        "Expanding": "Розширення",
        "Expansion": "Розширення",
        "Expect": "Очікувати",
        "Expected": "Очікуваний",
        "Expecting": "Очікування",
        "Expects": "Очікує",
        "Experience": "Досвід",
        "Experienced": "Досвідчений",
        "Experiences": "Досвід",
        "Experiencing": "Переживання",
        "Experiment": "Експеримент",
        "Experimental": "Експериментальний",
        "Experiments": "Експерименти",
        "Expert": "Експерт",
        "Experts": "Експерти",
        "Expire": "Закінчитися",
        "Expired": "Закінчився",
        "Expires": "Закінчується",
        "Expiring": "Закінчення",
        "Expiry": "Закінчення",
        "Explain": "Пояснити",
        "Explained": "Пояснено",
        "Explaining": "Пояснення",
        "Explanation": "Пояснення",
        "Explanations": "Пояснення",
        "Explains": "Пояснює",
        "Explicit": "Явний",
        "Explicitly": "Явно",
        "Export": "Експорт",
        "Exported": "Експортовано",
        "Exporting": "Експортування",
        "Exports": "Експорти",
        "Express": "Експрес",
        "Expression": "Вираз",
        "Expressions": "Вирази",
        "Extended": "Розширений",
        "Extending": "Розширення",
        "Extension": "Розширення",
        "Extensions": "Розширення",
        "Extensive": "Обширний",
        "Extent": "Ступінь",
        "External": "Зовнішній",
        "Externally": "Зовні",
        "Extra": "Додатковий",
        "Extract": "Витягти",
        "Extracted": "Витягнуто",
        "Extracting": "Витягування",
        "Extraction": "Витягування",
        "Extreme": "Екстремальний",
        "Extremely": "Надзвичайно"
    }
    
    translated_count = 0
    
    for english, ukrainian in translations.items():
        # Pattern to match exact msgid with the English text
        pattern = f'msgid "{english}"\nmsgstr ""'
        replacement = f'msgid "{english}"\nmsgstr "{ukrainian}"'
        
        if pattern in content:
            content = content.replace(pattern, replacement)
            translated_count += 1
            print(f"Translated: {english} -> {ukrainian}")
    
    # Write back the file
    with open('uk_UA.po', 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"\nTotal batch 2 translations made: {translated_count}")
    return translated_count

if __name__ == "__main__":
    print("Starting batch 2 translation...")
    translate_batch2_terms()
    print("Batch 2 translation complete!")

