#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Batch Ukrainian translation script for OPNsense
Translates simple terms directly in the PO file
"""

import re
import sys

def translate_batch_terms():
    """Batch translate simple terms"""
    
    # Read the file
    with open('uk_UA.po', 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Dictionary of simple translations
    translations = {
        # Simple technical terms
        "A Schedule with this name already exists.": "Розклад з такою назвою вже існує.",
        "A VHID must be selected for this CARP VIP.": "Для цього CARP VIP потрібно вибрати VHID.",
        "A certificate is required for tls types": "Для типів tls потрібен сертифікат",
        "A member interface passed does not exist in configuration": "Переданий інтерфейс-член не існує в конфігурації",
        "A numeric value must be specified for DPD delay.": "Для затримки DPD потрібно вказати числове значення.",
        "A numeric value must be specified for DPD retries.": "Для повторів DPD потрібно вказати числове значення.",
        "A password is required.": "Потрібен пароль.",
        "A password to encrypt your configuration": "Пароль для шифрування вашої конфігурації",
        "A prefix longer than 28 cannot be used with a net30 topology.": "Префікс довший за 28 не можна використовувати з топологією net30.",
        "A prefix longer than 29 cannot be used for tunnel network.": "Префікс довший за 29 не можна використовувати для тунельної мережі.",
        "A search domain may only contain the characters a-z, 0-9, '-' and '.'.": "Домен пошуку може містити лише символи a-z, 0-9, '-' та '.'.",
        "A server name must be provided.": "Потрібно вказати ім'я сервера.",
        "A short problem description or steps to reproduce.": "Короткий опис проблеми або кроки для відтворення.",
        "A snapshot already exists by this name": "Знімок з такою назвою вже існує",
        "A token lifetime requires a non zero Renegotiate time.": "Час життя токена вимагає ненульового часу перепогодження.",
        "A track interface is only allowed without an external prefix.": "Інтерфейс відстеження дозволений лише без зовнішнього префікса.",
        
        # Simple words and phrases
        "About": "Про програму",
        "Above": "Вище",
        "Absolute": "Абсолютний",
        "Accept": "Прийняти",
        "Accepted": "Прийнято",
        "Access": "Доступ",
        "Account": "Обліковий запис",
        "Accounting": "Облік",
        "Accuracy": "Точність",
        "Acknowledge": "Підтвердити",
        "Acknowledged": "Підтверджено",
        "Acquire": "Отримати",
        "Acquired": "Отримано",
        "Action": "Дія",
        "Actions": "Дії",
        "Activate": "Активувати",
        "Activated": "Активовано",
        "Active": "Активний",
        "Activity": "Активність",
        "Actual": "Фактичний",
        "Add": "Додати",
        "Added": "Додано",
        "Addition": "Додавання",
        "Additional": "Додатковий",
        "Address": "Адреса",
        "Addresses": "Адреси",
        "Admin": "Адміністратор",
        "Administration": "Адміністрування",
        "Administrative": "Адміністративний",
        "Administrator": "Адміністратор",
        "Advanced": "Розширений",
        "After": "Після",
        "Age": "Вік",
        "Agent": "Агент",
        "Aggregate": "Агрегат",
        "Aggregated": "Агреговано",
        "Aggregation": "Агрегація",
        "Alert": "Сповіщення",
        "Alerts": "Сповіщення",
        "Algorithm": "Алгоритм",
        "Algorithms": "Алгоритми",
        "Alias": "Псевдонім",
        "Aliases": "Псевдоніми",
        "All": "Все",
        "Allow": "Дозволити",
        "Allowed": "Дозволено",
        "Allowing": "Дозволяючи",
        "Always": "Завжди",
        "Amount": "Кількість",
        "Analysis": "Аналіз",
        "Analyze": "Аналізувати",
        "And": "І",
        "Anonymous": "Анонімний",
        "Answer": "Відповідь",
        "Answers": "Відповіді",
        "Any": "Будь-який",
        "API": "API",
        "Application": "Додаток",
        "Applications": "Додатки",
        "Apply": "Застосувати",
        "Applied": "Застосовано",
        "Applying": "Застосування",
        "Approach": "Підхід",
        "Approved": "Схвалено",
        "Archive": "Архів",
        "Archives": "Архіви",
        "Area": "Область",
        "Areas": "Області",
        "Argument": "Аргумент",
        "Arguments": "Аргументи",
        "Array": "Масив",
        "Arrays": "Масиви",
        "Article": "Стаття",
        "Articles": "Статті",
        "As": "Як",
        "Assign": "Призначити",
        "Assigned": "Призначено",
        "Assignment": "Призначення",
        "Assignments": "Призначення",
        "Associate": "Асоціювати",
        "Associated": "Асоційовано",
        "Association": "Асоціація",
        "Associations": "Асоціації",
        "Assume": "Припустити",
        "Assumed": "Припущено",
        "Asynchronous": "Асинхронний",
        "At": "В",
        "Attach": "Прикріпити",
        "Attached": "Прикріплено",
        "Attachment": "Вкладення",
        "Attachments": "Вкладення",
        "Attack": "Атака",
        "Attacks": "Атаки",
        "Attempt": "Спроба",
        "Attempts": "Спроби",
        "Attribute": "Атрибут",
        "Attributes": "Атрибути",
        "Audio": "Аудіо",
        "Audit": "Аудит",
        "Auditing": "Аудит",
        "Auth": "Автентифікація",
        "Authenticate": "Автентифікувати",
        "Authenticated": "Автентифіковано",
        "Authentication": "Автентифікація",
        "Author": "Автор",
        "Authority": "Орган",
        "Authorization": "Авторизація",
        "Authorize": "Авторизувати",
        "Authorized": "Авторизовано",
        "Auto": "Авто",
        "Automatic": "Автоматичний",
        "Automatically": "Автоматично",
        "Automation": "Автоматизація",
        "Available": "Доступний",
        "Average": "Середній",
        "Avoid": "Уникати",
        "Away": "Відсутній",
        
        # Network terms
        "Backup": "Резервна копія",
        "Backups": "Резервні копії",
        "Bad": "Поганий",
        "Balance": "Баланс",
        "Balanced": "Збалансований",
        "Balancing": "Балансування",
        "Ban": "Заборонити",
        "Bandwidth": "Пропускна здатність",
        "Banner": "Банер",
        "Base": "База",
        "Based": "Базований",
        "Basic": "Базовий",
        "Batch": "Пакет",
        "Battery": "Батарея",
        "Before": "Перед",
        "Begin": "Почати",
        "Beginning": "Початок",
        "Behavior": "Поведінка",
        "Below": "Нижче",
        "Best": "Найкращий",
        "Between": "Між",
        "Binary": "Двійковий",
        "Bind": "Прив'язати",
        "Binding": "Прив'язка",
        "Bit": "Біт",
        "Bits": "Біти",
        "Block": "Блок",
        "Blocked": "Заблоковано",
        "Blocking": "Блокування",
        "Blocks": "Блоки",
        "Board": "Плата",
        "Body": "Тіло",
        "Boot": "Завантаження",
        "Border": "Межа",
        "Both": "Обидва",
        "Bottom": "Низ",
        "Bound": "Прив'язаний",
        "Box": "Поле",
        "Branch": "Гілка",
        "Break": "Перерва",
        "Bridge": "Міст",
        "Bridged": "Мостовий",
        "Bridging": "Мостування",
        "Brief": "Короткий",
        "Bring": "Принести",
        "Broadcast": "Широкомовлення",
        "Broadcasting": "Широкомовлення",
        "Browse": "Переглянути",
        "Browser": "Браузер",
        "Buffer": "Буфер",
        "Buffered": "Буферизовано",
        "Buffering": "Буферизація",
        "Build": "Збірка",
        "Building": "Будівництво",
        "Built": "Побудовано",
        "Bundle": "Пакет",
        "Bundled": "Упаковано",
        "Business": "Бізнес",
        "Button": "Кнопка",
        "Buttons": "Кнопки",
        "By": "За",
        "Byte": "Байт",
        
        # System terms
        "Cache": "Кеш",
        "Cached": "Кешовано",
        "Caching": "Кешування",
        "Calculate": "Обчислити",
        "Calculated": "Обчислено",
        "Calculation": "Обчислення",
        "Calendar": "Календар",
        "Call": "Виклик",
        "Called": "Викликано",
        "Calling": "Виклик",
        "Calls": "Виклики",
        "Can": "Може",
        "Cancel": "Скасувати",
        "Cancelled": "Скасовано",
        "Cannot": "Не може",
        "Capability": "Можливість",
        "Capable": "Здатний",
        "Capacity": "Ємність",
        "Capital": "Капітал",
        "Card": "Карта",
        "Cards": "Карти",
        "Care": "Турбота",
        "Careful": "Обережний",
        "Carefully": "Обережно",
        "Carry": "Нести",
        "Case": "Випадок",
        "Cases": "Випадки",
        "Category": "Категорія",
        "Categories": "Категорії",
        "Cause": "Причина",
        "Caused": "Спричинено",
        "Causes": "Причини",
        "Causing": "Спричинення",
        "Caution": "Обережно",
        "Cell": "Комірка",
        "Cells": "Комірки",
        "Center": "Центр",
        "Central": "Центральний",
        "Centralized": "Централізований",
        "Centre": "Центр",
        "Certificate": "Сертифікат",
        "Certificates": "Сертифікати",
        "Certification": "Сертифікація",
        "Certified": "Сертифікований",
        "Chain": "Ланцюг",
        "Chained": "Ланцюговий",
        "Chains": "Ланцюги",
        "Challenge": "Виклик",
        "Challenges": "Виклики",
        "Change": "Змінити",
        "Changed": "Змінено",
        "Changes": "Зміни",
        "Changing": "Зміна",
        "Channel": "Канал",
        "Channels": "Канали",
        "Character": "Символ",
        "Characters": "Символи",
        "Characteristic": "Характеристика",
        "Characteristics": "Характеристики",
        "Charge": "Заряд",
        "Charged": "Заряджено",
        "Charging": "Зарядка",
        "Chart": "Діаграма",
        "Charts": "Діаграми",
        "Check": "Перевірити",
        "Checked": "Перевірено",
        "Checking": "Перевірка",
        "Checks": "Перевірки",
        "Checksum": "Контрольна сума",
        "Checksums": "Контрольні суми",
        "Choice": "Вибір",
        "Choices": "Вибори",
        "Choose": "Вибрати",
        "Chosen": "Вибрано",
        "Cipher": "Шифр",
        "Ciphers": "Шифри",
        "Circle": "Коло",
        "Circuit": "Схема",
        "Circuits": "Схеми",
        "Class": "Клас",
        "Classes": "Класи",
        "Classification": "Класифікація",
        "Classified": "Класифіковано",
        "Clean": "Очистити",
        "Cleaned": "Очищено",
        "Cleaning": "Очищення",
        "Clear": "Очистити",
        "Cleared": "Очищено",
        "Clearing": "Очищення",
        "Click": "Натиснути",
        "Clicked": "Натиснуто",
        "Clicking": "Натискання",
        "Client": "Клієнт",
        "Clients": "Клієнти",
        "Clock": "Годинник",
        "Close": "Закрити",
        "Closed": "Закрито",
        "Closing": "Закриття",
        "Cloud": "Хмара",
        "Cluster": "Кластер",
        "Clustered": "Кластеризовано",
        "Clustering": "Кластеризація",
        "Clusters": "Кластери",
        "Code": "Код",
        "Coded": "Закодовано",
        "Codes": "Коди",
        "Coding": "Кодування",
        "Cold": "Холодний",
        "Collect": "Зібрати",
        "Collected": "Зібрано",
        "Collecting": "Збирання",
        "Collection": "Колекція",
        "Collections": "Колекції",
        "Color": "Колір",
        "Colors": "Кольори",
        "Column": "Стовпець",
        "Columns": "Стовпці",
        "Combination": "Комбінація",
        "Combinations": "Комбінації",
        "Combine": "Об'єднати",
        "Combined": "Об'єднано",
        "Combining": "Об'єднання",
        "Come": "Прийти",
        "Coming": "Прихід",
        "Command": "Команда",
        "Commands": "Команди",
        "Comment": "Коментар",
        "Comments": "Коментарі",
        "Commercial": "Комерційний",
        "Common": "Загальний",
        "Commonly": "Зазвичай",
        "Communication": "Зв'язок",
        "Communications": "Зв'язок",
        "Community": "Спільнота",
        "Compact": "Компактний",
        "Company": "Компанія",
        "Compare": "Порівняти",
        "Compared": "Порівняно",
        "Comparing": "Порівняння",
        "Comparison": "Порівняння",
        "Comparisons": "Порівняння",
        "Compatible": "Сумісний",
        "Compatibility": "Сумісність",
        "Compile": "Компілювати",
        "Compiled": "Скомпільовано",
        "Compiler": "Компілятор",
        "Compiling": "Компіляція",
        "Complete": "Завершити",
        "Completed": "Завершено",
        "Completely": "Повністю",
        "Completing": "Завершення",
        "Completion": "Завершення",
        "Complex": "Складний",
        "Complexity": "Складність",
        "Component": "Компонент",
        "Components": "Компоненти",
        "Compose": "Скласти",
        "Composed": "Складено",
        "Composition": "Композиція",
        "Compress": "Стиснути",
        "Compressed": "Стиснуто",
        "Compression": "Стиснення",
        "Compute": "Обчислити",
        "Computed": "Обчислено",
        "Computer": "Комп'ютер",
        "Computers": "Комп'ютери",
        "Computing": "Обчислення",
        "Concept": "Концепція",
        "Concepts": "Концепції",
        "Concern": "Турбота",
        "Concerned": "Стурбований",
        "Concerning": "Стосовно",
        "Concerns": "Турботи",
        "Condition": "Умова",
        "Conditional": "Умовний",
        "Conditions": "Умови",
        "Configure": "Налаштувати",
        "Configured": "Налаштовано",
        "Configuring": "Налаштування",
        "Configuration": "Конфігурація",
        "Configurations": "Конфігурації",
        "Confirm": "Підтвердити",
        "Confirmation": "Підтвердження",
        "Confirmed": "Підтверджено",
        "Confirming": "Підтвердження",
        "Conflict": "Конфлікт",
        "Conflicts": "Конфлікти",
        "Connect": "Підключити",
        "Connected": "Підключено",
        "Connecting": "Підключення",
        "Connection": "З'єднання",
        "Connections": "З'єднання",
        "Connectivity": "Підключення",
        "Connector": "З'єднувач",
        "Connectors": "З'єднувачі",
        "Connects": "Підключає",
        "Consider": "Розглянути",
        "Consideration": "Розгляд",
        "Considered": "Розглянуто",
        "Considering": "Розглядаючи",
        "Consistent": "Послідовний",
        "Consistently": "Послідовно",
        "Console": "Консоль",
        "Consoles": "Консолі",
        "Constant": "Константа",
        "Constants": "Константи",
        "Construct": "Конструкція",
        "Constructed": "Побудовано",
        "Construction": "Будівництво",
        "Constructs": "Конструкції",
        "Consume": "Споживати",
        "Consumed": "Спожито",
        "Consumer": "Споживач",
        "Consumers": "Споживачі",
        "Consuming": "Споживання",
        "Consumption": "Споживання",
        "Contact": "Контакт",
        "Contacts": "Контакти",
        "Contain": "Містити",
        "Contained": "Міститься",
        "Container": "Контейнер",
        "Containers": "Контейнери",
        "Containing": "Містить",
        "Contains": "Містить",
        "Content": "Вміст",
        "Contents": "Вміст",
        "Context": "Контекст",
        "Contexts": "Контексти",
        "Continue": "Продовжити",
        "Continued": "Продовжено",
        "Continues": "Продовжує",
        "Continuing": "Продовження",
        "Continuous": "Безперервний",
        "Continuously": "Безперервно",
        "Contract": "Контракт",
        "Contracts": "Контракти",
        "Control": "Контроль",
        "Controlled": "Контрольовано",
        "Controller": "Контролер",
        "Controllers": "Контролери",
        "Controlling": "Контролювання",
        "Controls": "Елементи керування",
        "Convenient": "Зручний",
        "Convention": "Конвенція",
        "Conventions": "Конвенції",
        "Conventional": "Звичайний",
        "Conversation": "Розмова",
        "Conversations": "Розмови",
        "Convert": "Перетворити",
        "Converted": "Перетворено",
        "Converting": "Перетворення",
        "Conversion": "Перетворення",
        "Conversions": "Перетворення",
        "Converter": "Конвертер",
        "Converters": "Конвертери",
        "Converts": "Перетворює",
        "Cookie": "Кукі",
        "Cookies": "Кукі",
        "Cool": "Прохолодний",
        "Cooling": "Охолодження",
        "Copy": "Копіювати",
        "Copied": "Скопійовано",
        "Copies": "Копії",
        "Copying": "Копіювання",
        "Core": "Ядро",
        "Cores": "Ядра",
        "Corner": "Кут",
        "Corners": "Кути",
        "Correct": "Правильний",
        "Corrected": "Виправлено",
        "Correcting": "Виправлення",
        "Correction": "Виправлення",
        "Corrections": "Виправлення",
        "Correctly": "Правильно",
        "Correspond": "Відповідати",
        "Correspondence": "Відповідність",
        "Corresponding": "Відповідний",
        "Corresponds": "Відповідає",
        "Cost": "Вартість",
        "Costs": "Витрати",
        "Could": "Міг",
        "Count": "Кількість",
        "Counted": "Підраховано",
        "Counter": "Лічильник",
        "Counters": "Лічильники",
        "Counting": "Підрахунок",
        "Counts": "Підраховує",
        "Country": "Країна",
        "Countries": "Країни",
        "Couple": "Пара",
        "Coupled": "Пов'язано",
        "Couples": "Пари",
        "Coupling": "Зв'язок",
        "Course": "Курс",
        "Courses": "Курси",
        "Cover": "Покрити",
        "Coverage": "Покриття",
        "Covered": "Покрито",
        "Covering": "Покриття",
        "Covers": "Покриває",
        "CPU": "Процесор",
        "CPUs": "Процесори",
        "Crash": "Збій",
        "Crashed": "Зламався",
        "Crashes": "Збої",
        "Crashing": "Збій",
        "Create": "Створити",
        "Created": "Створено",
        "Creates": "Створює",
        "Creating": "Створення",
        "Creation": "Створення",
        "Creative": "Творчий",
        "Credential": "Облікові дані",
        "Credentials": "Облікові дані",
        "Critical": "Критичний",
        "Critically": "Критично",
        "Cross": "Перехрестя",
        "Crossed": "Перетнуто",
        "Crossing": "Перетин",
        "Cryptographic": "Криптографічний",
        "Cryptography": "Криптографія",
        "Current": "Поточний",
        "Currently": "Наразі",
        "Cursor": "Курсор",
        "Curve": "Крива",
        "Curves": "Криві",
        "Custom": "Користувацький",
        "Customer": "Клієнт",
        "Customers": "Клієнти",
        "Customization": "Налаштування",
        "Customize": "Налаштувати",
        "Customized": "Налаштовано",
        "Customizing": "Налаштування",
        "Cut": "Вирізати",
        "Cutting": "Вирізання",
        "Cycle": "Цикл",
        "Cycles": "Цикли",
        "Cycling": "Циклічність"
    }
    
    translated_count = 0
    
    for english, ukrainian in translations.items():
        # Pattern to match exact msgid with the English text
        pattern = f'msgid "{english}"\nmsgstr ""'
        replacement = f'msgid "{english}"\nmsgstr "{ukrainian}"'
        
        if pattern in content:
            content = content.replace(pattern, replacement)
            translated_count += 1
            print(f"Translated: {english} -> {ukrainian}")
    
    # Write back the file
    with open('uk_UA.po', 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"\nTotal batch translations made: {translated_count}")
    return translated_count

if __name__ == "__main__":
    print("Starting batch translation...")
    translate_batch_terms()
    print("Batch translation complete!")

