#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Extended Ukrainian translation script for OPNsense
Translates more terms including technical and interface elements
"""

import re
import sys

# Extended dictionary of translations
extended_translations = {
    # Additional basic actions
    "Abort": "Перервати",
    "Activate": "Активувати",
    "Accessed": "Доступ отримано",
    "Adaptive": "Адаптивний",
    "Addresses": "Адреси",
    "Adress": "Адреса",  # Note: this is a typo in original, but we translate it
    "Age": "Вік",
    "Alias": "Псевдонім",
    "Allowed": "Дозволено",
    "Answer": "Відповідь",
    "Antispam": "Антиспам",
    "Antivirus": "Антивірус",
    "Anywhere": "Будь-де",
    "Architecture": "Архітектура",
    "Archive": "Архів",
    "Assisted": "З допомогою",
    "Attribute": "Атрибут",
    "Authority": "Орган",
    "Avg": "Сер.",
    "Back": "Назад",
    "Best": "Найкращий",
    "Bitmask": "Бітова маска",
    "Blocked": "Заблоковано",
    "Boolean": "Логічний",
    "Bpf": "BPF",
    "Branch": "Гілка",
    "Browse": "Переглянути",
    "Build": "Збірка",
    "Bundle": "Пакет",
    "Button": "Кнопка",
    "Cache": "Кеш",
    "Calculate": "Обчислити",
    "Calendar": "Календар",
    "Callback": "Зворотний виклик",
    "Capacity": "Ємність",
    "Category": "Категорія",
    "Certificate": "Сертифікат",
    "Chain": "Ланцюг",
    "Challenge": "Виклик",
    "Change": "Змінити",
    "Channel": "Канал",
    "Character": "Символ",
    "Check": "Перевірити",
    "Checksum": "Контрольна сума",
    "Choose": "Вибрати",
    "Cipher": "Шифр",
    "Class": "Клас",
    "Client": "Клієнт",
    "Clock": "Годинник",
    "Code": "Код",
    "Column": "Стовпець",
    "Command": "Команда",
    "Comment": "Коментар",
    "Common": "Загальний",
    "Community": "Спільнота",
    "Compare": "Порівняти",
    "Complete": "Завершити",
    "Component": "Компонент",
    "Compress": "Стиснути",
    "Computer": "Комп'ютер",
    "Condition": "Умова",
    "Connect": "Підключити",
    "Connection": "З'єднання",
    "Console": "Консоль",
    "Contact": "Контакт",
    "Container": "Контейнер",
    "Content": "Вміст",
    "Context": "Контекст",
    "Control": "Керування",
    "Cookie": "Кукі",
    "Core": "Ядро",
    "Country": "Країна",
    "Create": "Створити",
    "Cron": "Cron",
    "Current": "Поточний",
    "Curve": "Крива",
    "Custom": "Користувацький",
    "Daemon": "Демон",
    "Database": "База даних",
    "Debug": "Налагодження",
    "Decode": "Декодувати",
    "Decrypt": "Розшифрувати",
    "Default": "За замовчуванням",
    "Delay": "Затримка",
    "Deliver": "Доставити",
    "Deny": "Заборонити",
    "Deploy": "Розгорнути",
    "Depth": "Глибина",
    "Destination": "Призначення",
    "Detail": "Деталь",
    "Device": "Пристрій",
    "Digest": "Дайджест",
    "Direct": "Прямий",
    "Directory": "Каталог",
    "Disconnect": "Відключити",
    "Display": "Відображення",
    "Domain": "Домен",
    "Download": "Завантажити",
    "Driver": "Драйвер",
    "Drop": "Відкинути",
    "Duration": "Тривалість",
    "Dynamic": "Динамічний",
    "Echo": "Ехо",
    "Encode": "Кодувати",
    "Encrypt": "Зашифрувати",
    "Engine": "Двигун",
    "Entry": "Запис",
    "Error": "Помилка",
    "Event": "Подія",
    "Example": "Приклад",
    "Exchange": "Обмін",
    "Execute": "Виконати",
    "Exist": "Існує",
    "Exit": "Вихід",
    "Expand": "Розгорнути",
    "Expire": "Закінчитися",
    "Export": "Експорт",
    "Expression": "Вираз",
    "Extension": "Розширення",
    "External": "Зовнішній",
    "Extract": "Витягти",
    "Factor": "Фактор",
    "Failed": "Невдало",
    "Family": "Сімейство",
    "Fast": "Швидкий",
    "Feature": "Функція",
    "Field": "Поле",
    "Filter": "Фільтр",
    "Find": "Знайти",
    "Fingerprint": "Відбиток",
    "Firewall": "Брандмауер",
    "First": "Перший",
    "Fix": "Виправити",
    "Flag": "Прапор",
    "Flow": "Потік",
    "Folder": "Папка",
    "Force": "Примусити",
    "Format": "Формат",
    "Forward": "Переслати",
    "Fragment": "Фрагмент",
    "Frame": "Кадр",
    "Frequency": "Частота",
    "Function": "Функція",
    "Gateway": "Шлюз",
    "Generate": "Згенерувати",
    "Global": "Глобальний",
    "Graph": "Графік",
    "Group": "Група",
    "Guard": "Охорона",
    "Guest": "Гість",
    "Guide": "Посібник",
    "Handle": "Обробити",
    "Hardware": "Апаратне забезпечення",
    "Hash": "Хеш",
    "Header": "Заголовок",
    "Health": "Здоров'я",
    "Height": "Висота",
    "History": "Історія",
    "Home": "Головна",
    "Hook": "Гачок",
    "Host": "Хост",
    "Hostname": "Ім'я хоста",
    "Hour": "Година",
    "Icon": "Іконка",
    "Identity": "Ідентичність",
    "Image": "Зображення",
    "Import": "Імпорт",
    "Include": "Включити",
    "Index": "Індекс",
    "Info": "Інформація",
    "Initial": "Початковий",
    "Input": "Ввід",
    "Install": "Встановити",
    "Instance": "Екземпляр",
    "Instruction": "Інструкція",
    "Interface": "Інтерфейс",
    "Internal": "Внутрішній",
    "Internet": "Інтернет",
    "Interval": "Інтервал",
    "Invalid": "Недійсний",
    "Item": "Елемент",
    "Job": "Завдання",
    "Join": "Приєднатися",
    "Journal": "Журнал",
    "Jump": "Перейти",
    "Keep": "Зберегти",
    "Kernel": "Ядро",
    "Key": "Ключ",
    "Keyword": "Ключове слово",
    "Kill": "Вбити",
    "Label": "Мітка",
    "Language": "Мова",
    "Last": "Останній",
    "Launch": "Запустити",
    "Layer": "Шар",
    "Layout": "Макет",
    "Length": "Довжина",
    "Level": "Рівень",
    "Library": "Бібліотека",
    "License": "Ліцензія",
    "Limit": "Обмеження",
    "Line": "Рядок",
    "Link": "Посилання",
    "List": "Список",
    "Listen": "Слухати",
    "Load": "Завантажити",
    "Local": "Локальний",
    "Location": "Розташування",
    "Lock": "Заблокувати",
    "Login": "Вхід",
    "Logout": "Вихід",
    "Loop": "Цикл",
    "Machine": "Машина",
    "Magic": "Магічний",
    "Mail": "Пошта",
    "Main": "Головний",
    "Manage": "Керувати",
    "Manager": "Менеджер",
    "Manual": "Посібник",
    "Map": "Карта",
    "Mark": "Позначити",
    "Mask": "Маска",
    "Master": "Головний",
    "Match": "Збіг",
    "Maximum": "Максимум",
    "Mean": "Середнє",
    "Measure": "Виміряти",
    "Media": "Медіа",
    "Member": "Член",
    "Memory": "Пам'ять",
    "Menu": "Меню",
    "Message": "Повідомлення",
    "Method": "Метод",
    "Metric": "Метрика",
    "Minimum": "Мінімум",
    "Minor": "Незначний",
    "Minute": "Хвилина",
    "Mirror": "Дзеркало",
    "Missing": "Відсутній",
    "Mode": "Режим",
    "Model": "Модель",
    "Module": "Модуль",
    "Monitor": "Монітор",
    "Month": "Місяць",
    "Mount": "Монтувати",
    "Move": "Перемістити",
    "Multiple": "Множинний",
    "Native": "Рідний",
    "Navigate": "Навігувати",
    "Network": "Мережа",
    "Next": "Наступний",
    "Node": "Вузол",
    "Normal": "Нормальний",
    "Note": "Примітка",
    "Notice": "Повідомлення",
    "Number": "Номер",
    "Object": "Об'єкт",
    "Obtain": "Отримати",
    "Office": "Офіс",
    "Online": "В мережі",
    "Open": "Відкрити",
    "Operation": "Операція",
    "Option": "Опція",
    "Order": "Порядок",
    "Origin": "Походження",
    "Original": "Оригінальний",
    "Output": "Вивід",
    "Override": "Перевизначити",
    "Owner": "Власник",
    "Package": "Пакет",
    "Page": "Сторінка",
    "Panel": "Панель",
    "Parameter": "Параметр",
    "Parent": "Батьківський",
    "Parse": "Розібрати",
    "Part": "Частина",
    "Pass": "Пройти",
    "Password": "Пароль",
    "Path": "Шлях",
    "Pattern": "Шаблон",
    "Pause": "Пауза",
    "Payload": "Корисне навантаження",
    "Peer": "Однорангова мережа",
    "Pending": "Очікує",
    "Percent": "Відсоток",
    "Perfect": "Ідеальний",
    "Period": "Період",
    "Permission": "Дозвіл",
    "Phase": "Фаза",
    "Phone": "Телефон",
    "Physical": "Фізичний",
    "Picture": "Зображення",
    "Piece": "Частина",
    "Ping": "Пінг",
    "Place": "Місце",
    "Plan": "План",
    "Platform": "Платформа",
    "Play": "Грати",
    "Plugin": "Плагін",
    "Point": "Точка",
    "Policy": "Політика",
    "Pool": "Пул",
    "Port": "Порт",
    "Position": "Позиція",
    "Post": "Повідомлення",
    "Power": "Потужність",
    "Prefix": "Префікс",
    "Present": "Присутній",
    "Press": "Натиснути",
    "Previous": "Попередній",
    "Primary": "Основний",
    "Print": "Друкувати",
    "Priority": "Пріоритет",
    "Private": "Приватний",
    "Problem": "Проблема",
    "Process": "Процес",
    "Product": "Продукт",
    "Profile": "Профіль",
    "Program": "Програма",
    "Project": "Проект",
    "Property": "Властивість",
    "Protocol": "Протокол",
    "Provide": "Надати",
    "Provider": "Постачальник",
    "Proxy": "Проксі",
    "Public": "Публічний",
    "Publish": "Опублікувати",
    "Pull": "Витягти",
    "Purpose": "Мета",
    "Push": "Натиснути",
    "Quality": "Якість",
    "Query": "Запит",
    "Queue": "Черга",
    "Quick": "Швидкий",
    "Quiet": "Тихий",
    "Quote": "Цитата",
    "Random": "Випадковий",
    "Range": "Діапазон",
    "Rate": "Швидкість",
    "Raw": "Сирий",
    "Read": "Читати",
    "Ready": "Готовий",
    "Real": "Справжній",
    "Reason": "Причина",
    "Receive": "Отримати",
    "Recent": "Останній",
    "Record": "Запис",
    "Recover": "Відновити",
    "Redirect": "Перенаправити",
    "Reduce": "Зменшити",
    "Reference": "Посилання",
    "Refresh": "Оновити",
    "Region": "Регіон",
    "Register": "Зареєструвати",
    "Regular": "Регулярний",
    "Reject": "Відхилити",
    "Related": "Пов'язаний",
    "Release": "Реліз",
    "Reload": "Перезавантажити",
    "Remote": "Віддалений",
    "Remove": "Видалити",
    "Rename": "Перейменувати",
    "Repeat": "Повторити",
    "Replace": "Замінити",
    "Reply": "Відповісти",
    "Report": "Звіт",
    "Request": "Запит",
    "Require": "Вимагати",
    "Reserve": "Зарезервувати",
    "Reset": "Скинути",
    "Resolve": "Вирішити",
    "Resource": "Ресурс",
    "Response": "Відповідь",
    "Restart": "Перезапустити",
    "Restore": "Відновити",
    "Result": "Результат",
    "Resume": "Продовжити",
    "Retry": "Повторити",
    "Return": "Повернути",
    "Reverse": "Зворотний",
    "Review": "Переглянути",
    "Revoke": "Відкликати",
    "Right": "Правий",
    "Risk": "Ризик",
    "Role": "Роль",
    "Root": "Корінь",
    "Rotate": "Обертати",
    "Round": "Раунд",
    "Route": "Маршрут",
    "Router": "Маршрутизатор",
    "Routing": "Маршрутизація",
    "Row": "Рядок",
    "Rule": "Правило",
    "Run": "Запустити",
    "Safe": "Безпечний",
    "Sample": "Зразок",
    "Save": "Зберегти",
    "Scale": "Масштаб",
    "Scan": "Сканувати",
    "Schedule": "Розклад",
    "Schema": "Схема",
    "Scope": "Область",
    "Score": "Оцінка",
    "Screen": "Екран",
    "Script": "Скрипт",
    "Search": "Пошук",
    "Second": "Секунда",
    "Secret": "Секрет",
    "Section": "Розділ",
    "Secure": "Безпечний",
    "Security": "Безпека",
    "Select": "Вибрати",
    "Send": "Надіслати",
    "Sequence": "Послідовність",
    "Serial": "Серійний",
    "Series": "Серія",
    "Server": "Сервер",
    "Service": "Служба",
    "Session": "Сесія",
    "Setting": "Налаштування",
    "Setup": "Налаштування",
    "Share": "Поділитися",
    "Shell": "Оболонка",
    "Show": "Показати",
    "Shutdown": "Вимкнути",
    "Signal": "Сигнал",
    "Simple": "Простий",
    "Single": "Одиночний",
    "Site": "Сайт",
    "Size": "Розмір",
    "Skip": "Пропустити",
    "Slave": "Підлеглий",
    "Sleep": "Сон",
    "Slow": "Повільний",
    "Small": "Малий",
    "Smart": "Розумний",
    "Snapshot": "Знімок",
    "Socket": "Сокет",
    "Software": "Програмне забезпечення",
    "Solution": "Рішення",
    "Sort": "Сортувати",
    "Source": "Джерело",
    "Space": "Простір",
    "Special": "Спеціальний",
    "Speed": "Швидкість",
    "Split": "Розділити",
    "Stable": "Стабільний",
    "Stack": "Стек",
    "Stage": "Етап",
    "Standard": "Стандарт",
    "Start": "Початок",
    "State": "Стан",
    "Static": "Статичний",
    "Station": "Станція",
    "Statistics": "Статистика",
    "Status": "Статус",
    "Step": "Крок",
    "Stop": "Зупинити",
    "Storage": "Сховище",
    "Store": "Зберігати",
    "Stream": "Потік",
    "String": "Рядок",
    "Strong": "Сильний",
    "Structure": "Структура",
    "Style": "Стиль",
    "Subject": "Тема",
    "Submit": "Надіслати",
    "Success": "Успіх",
    "Summary": "Підсумок",
    "Support": "Підтримка",
    "Switch": "Перемикач",
    "Symbol": "Символ",
    "Sync": "Синхронізувати",
    "System": "Система",
    "Table": "Таблиця",
    "Tag": "Тег",
    "Target": "Ціль",
    "Task": "Завдання",
    "Team": "Команда",
    "Technical": "Технічний",
    "Technology": "Технологія",
    "Template": "Шаблон",
    "Term": "Термін",
    "Terminal": "Термінал",
    "Test": "Тест",
    "Text": "Текст",
    "Theme": "Тема",
    "Thread": "Потік",
    "Threshold": "Поріг",
    "Ticket": "Квиток",
    "Time": "Час",
    "Timeout": "Тайм-аут",
    "Timer": "Таймер",
    "Title": "Заголовок",
    "Token": "Токен",
    "Tool": "Інструмент",
    "Topic": "Тема",
    "Total": "Всього",
    "Touch": "Торкнутися",
    "Track": "Відстежити",
    "Traffic": "Трафік",
    "Transfer": "Передача",
    "Transform": "Перетворити",
    "Translate": "Перекласти",
    "Transport": "Транспорт",
    "Tree": "Дерево",
    "Trigger": "Тригер",
    "Trust": "Довіра",
    "Try": "Спробувати",
    "Tunnel": "Тунель",
    "Turn": "Повернути",
    "Type": "Тип",
    "Unique": "Унікальний",
    "Unit": "Одиниця",
    "Unknown": "Невідомий",
    "Unlock": "Розблокувати",
    "Unset": "Скасувати",
    "Update": "Оновити",
    "Upgrade": "Оновити",
    "Upload": "Завантажити",
    "Usage": "Використання",
    "User": "Користувач",
    "Utility": "Утиліта",
    "Valid": "Дійсний",
    "Value": "Значення",
    "Variable": "Змінна",
    "Vendor": "Постачальник",
    "Verify": "Перевірити",
    "Version": "Версія",
    "Video": "Відео",
    "View": "Переглянути",
    "Virtual": "Віртуальний",
    "Visible": "Видимий",
    "Visit": "Відвідати",
    "Volume": "Том",
    "Wait": "Чекати",
    "Wake": "Прокинутися",
    "Walk": "Йти",
    "Warning": "Попередження",
    "Watch": "Дивитися",
    "Way": "Шлях",
    "Web": "Веб",
    "Website": "Веб-сайт",
    "Week": "Тиждень",
    "Weight": "Вага",
    "Welcome": "Ласкаво просимо",
    "Wide": "Широкий",
    "Window": "Вікно",
    "Wire": "Дріт",
    "Wizard": "Майстер",
    "Work": "Робота",
    "World": "Світ",
    "Write": "Писати",
    "Year": "Рік",
    "Zone": "Зона"
}

def translate_po_file_extended(filename):
    """Translate extended terms in PO file"""
    with open(filename, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Count translations made
    translated_count = 0
    
    for english, ukrainian in extended_translations.items():
        # Pattern to match exact msgid with the English term
        pattern = f'msgid "{re.escape(english)}"\nmsgstr ""'
        replacement = f'msgid "{english}"\nmsgstr "{ukrainian}"'
        
        if pattern in content:
            content = content.replace(pattern, replacement)
            translated_count += 1
            print(f"Translated: {english} -> {ukrainian}")
    
    # Write back the file
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"\nTotal new translations made: {translated_count}")
    return translated_count

if __name__ == "__main__":
    filename = "uk_UA.po"
    if len(sys.argv) > 1:
        filename = sys.argv[1]
    
    print(f"Adding extended translations to {filename}...")
    translate_po_file_extended(filename)
    print("Extended translation complete!")

